# Generated by Django 5.1 on 2024-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(upload_to='banners/')),
                ('overlay_opacity', models.FloatField(default=0.5)),
                ('button_text', models.CharField(default='View Details', max_length=50)),
                ('button_link', models.URLField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
