# Generated by Django 5.1 on 2024-09-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_about_specialities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Specialities',
        ),
    ]
