# Generated by Django 5.1 on 2024-08-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SpiceEx', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='siteinfo/')),
                ('small_logo', models.ImageField(blank=True, null=True, upload_to='siteinfo/')),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='siteinfo.siteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='siteinfo.siteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='siteinfo.siteinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='siteinfo.siteinfo')),
            ],
        ),
    ]
