# Generated by Django 5.1 on 2024-09-01 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_phone_number', models.CharField(max_length=20)),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_phone_number', to='siteinfo.siteinfo')),
            ],
        ),
    ]
